import type { Metadata } from "next";

/**
 * Canonical origin for the site.
 *
 * Link previews need absolute URLs: WhatsApp in particular will not resolve a
 * relative og:image, and silently falls back to a text-only card when it sees
 * one. Next.js only emits absolute URLs once `metadataBase` is set, which the
 * root layout does from this value.
 */
export const SITE_URL = new URL(
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.genaie.site",
);

export const SITE_NAME = "Genaie";

/**
 * The shared link-preview card, regenerated by `npm run generate:og-image`.
 *
 * Declared explicitly rather than via Next's `app/opengraph-image.png` file
 * convention, because that convention only applies to the segment holding the
 * file: it covers `/` but leaves `/login`, `/pricing` and friends with no
 * image at all. The explicit width/height matter to WhatsApp, which uses them
 * to reserve the card's layout before the image finishes downloading.
 */
export const SITE_IMAGE = {
  url: "/og-card.png",
  width: 1200,
  height: 630,
  type: "image/png",
  alt: "Genaie — a robot assistant carrying a job application and a suitcase",
} as const;

type PageMetadataInput = {
  title: string;
  description: string;
  /** Route path, used for the canonical and og:url. */
  path: string;
};

/**
 * Builds a page's metadata with matching Open Graph and Twitter cards.
 *
 * Next.js merges metadata shallowly, so a page that declares its own
 * `openGraph` replaces the parent's wholesale — including the image. Routing
 * every page through this helper keeps the social tags from drifting apart as
 * pages are added.
 */
export function pageMetadata({ title, description, path }: PageMetadataInput): Metadata {
  const url = new URL(path, SITE_URL).toString();

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_US",
      type: "website",
      images: [SITE_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [SITE_IMAGE],
    },
  };
}
